# Generated by Django 5.0.6 on 2024-07-22 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('namaste_customer', '0003_ordermodel_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='on_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
